server:
  port: 9093

spring:
  profiles:
    active: local
  application:
    name: USER-SERVICE
  datasource:
    #db name: userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # if there is update on data, it will update existing tables, not to create a new one
      ddl-auto: update
    show-sql: true
    #    Convert based language to my SQL based query
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
